# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/server.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/server.proto\x12\x0cverification\"\x1f\n\rImageNamesReq\x12\x0e\n\x06images\x18\x01 \x03(\t\"\x1f\n\x0ePredictionsRes\x12\r\n\x05preds\x18\x01 \x03(\t2Y\n\x10\x42\x65n_Verification\x12\x45\n\x08SayHello\x12\x1b.verification.ImageNamesReq\x1a\x1c.verification.PredictionsResb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.server_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGENAMESREQ._serialized_start=36
  _IMAGENAMESREQ._serialized_end=67
  _PREDICTIONSRES._serialized_start=69
  _PREDICTIONSRES._serialized_end=100
  _BEN_VERIFICATION._serialized_start=102
  _BEN_VERIFICATION._serialized_end=191
# @@protoc_insertion_point(module_scope)
